# LIGHTS

# Lights off when everyone leaves the house
- alias: Nobody Home No Lights
  trigger: 
    platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
  condition: 
    - condition: time
      after: '09:30'
      before: '14:30'
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue_lightstrip
      data: 
        transition: 15
    - service: homeassistant.turn_off
      entity_id: light.hue_lightstrip2
      data: 
        transition: 15

# Backdoor light turns on when door is open
- alias: Backdoor light on
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001f3990c
    from: 'off'
    to: 'on'
  condition:
    condition: or  # 'when dark' condition: either after sunset or before sunrise - equivalent to a state condition on `sun.sun` of `below_horizon`
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise 
 #   - condition: time
 #     after: '17:00'
 #     before: '09:00'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.back_door_light
    - service: timer.start
      data:
        entity_id: timer.backdoor

# Backdoor light turns off when door is closed
- alias: Backdoor light off
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.backdoor
  action:
    service: homeassistant.turn_off
    entity_id: switch.back_door_light

# Front lights on at sunset
- alias: Turn on the lights when the sun sets
  hide_entity: True
  trigger:
    platform: sun
    event: sunset
    offset: "-00:20:00"
  action:
    service: homeassistant.turn_on
    entity_id: switch.front_door_light

# Front lights off at 9:00
- alias: 'Turn off Light at 830'
  trigger:
    platform: time
    at: '21:30'
  action:
   service: homeassistant.turn_off
   entity_id: switch.front_door_light

# Kitchen Light on with movement
- alias: Kitchen Motion Sensor Lights On
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001d69546
    to: 'on'
  condition:
    - condition: time
      after: '19:30'
      before: '08:30'
    - condition: state
      entity_id: light.hue_lightstrip
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: light.hue_lightstrip
      data: 
        transition: 15
        brightness_pct: 50
    - service: homeassistant.turn_on
      entity_id: light.hue_lightstrip2
      data: 
        transition: 15
        brightness_pct: 50
    - service: input_boolean.turn_on
      entity_id: input_boolean.lightstrip_auto_on

# Kitchen Light off with no movement
- alias: Kitchen Motion Sensor Lights Off
  initial_state: "on"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001d69546
    to: 'off'
    for:
      minutes: 3
  condition:
    - condition: state
      entity_id: input_boolean.lightstrip_auto_on
      state: 'on'
    - condition: time
      after: '19:30'
      before: '8:30'
    - condition: state
      entity_id: light.hue_lightstrip
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue_lightstrip
      data: 
        transition: 15
    - service: homeassistant.turn_off
      entity_id: light.hue_lightstrip2
      data: 
        transition: 15

# Kitchen Lightstrip Input Boolean
- alias: Switch turned off
  initial_state: "on"
  trigger:
    platform: state
    entity_id: light.hue_lightstrip
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.lightstrip_auto_on
    state: 'on'
  action:
      service: input_boolean.turn_off
      entity_id: input_boolean.lightstrip_auto_on

# Aaron button turns on Bedroom side table light - single click
- alias: Aaron Beside Table Light Single ON
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000210a061
      click_type: single
  condition: 
    condition: state
    entity_id: light.hue_bed
    state: 'off'
  action:
    service: light.turn_on
    data: 
      entity_id: light.hue_bed
      brightness_pct: 100

# Aaron Button turns off Bedroom side table light - single click
- alias: Aaron Beside Table Light Single OFF
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000210a061
      click_type: single
  condition: 
    condition: state
    entity_id: light.hue_bed
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hue_bed

# Aaron button on bedroom side table - double click - ON
- alias: Aaron Beside Table Light Double ON
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000210a061
      click_type: double
  condition: 
    condition: state
    entity_id: light.hue_bed
    state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.hue_bed
      brightness_pct: 25

# Aaron button on bedroom side table - double click - OFF
- alias: Aaron Beside Table Light Double OFF
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000210a061
      click_type: double
  condition: 
    condition: state
    entity_id: light.hue_bed
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hue_bed

# Erica's Light
 
# Erica button turns on Bedroom side table light - single click
- alias: Erica Beside Table Light Single ON
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002f81689
      click_type: single
  condition: 
    condition: state
    entity_id: light.hue_erica
    state: 'off'
  action:
    service: light.turn_on
    data: 
      entity_id: light.hue_erica
      brightness_pct: 100

# Erica Button turns off Bedroom side table light - single click
- alias: Erica Beside Table Light Single OFF
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002f81689
      click_type: single
  condition: 
    condition: state
    entity_id: light.hue_erica
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hue_erica

# Erica button on bedroom side table - double click - ON
- alias: Erica Beside Table Light Double ON
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002f81689
      click_type: double
  condition: 
    condition: state
    entity_id: light.hue_erica
    state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: light.hue_erica
      brightness_pct: 25

# Erica button on bedroom side table - double click - OFF
- alias: Erica Beside Table Light Double OFF
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002f81689
      click_type: double
  condition: 
    condition: state
    entity_id: light.hue_erica
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hue_erica

# When garage door opens at night - turn on bedside light
- alias: Backdoor light on
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d000224ff31
    from: 'off'
    to: 'on'
  condition: 
    condition: time
    after: '22:00:00'
    before: '07:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.hue_bed
    
