# Home Assistant Update
- alias: 'Update Available'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    service: notify.pushover
    data:
      message: 'Home Assistant update is available.'


